const express = require("express");
const router = express.Router();
const zodSchema = require("../validators/auth-validator");
const validate = require("../middlewares/auth-middleware");
const controllers = require("../controller/auth-controller");
router.route("/home").get(controllers.home);
router.route("/superadmin-register").post(validate(zodSchema.superAdminRegisterSchema),controllers.superAdminRegister);
router.route("/superadmin-login").post(validate(zodSchema.superAdminLoginSchema),controllers.superAdminLogin);
router.route("/admin-registration-by-sa").post(validate(zodSchema.registerDepartmentAdminSchema),controllers.registerDepartmentAdmin);
router.route("/admin-login").post(validate(zodSchema.adminLoginSchema),controllers.adminLogin);
router.route("/employee-registration-by-admin").post(validate(zodSchema.registerEmployeeSchema),controllers.registerEmployee);
router.route("/employee-login").post(validate(zodSchema.employeeLoginSchema),controllers.employeeLogin);
router.route("/change-sa-password").post(validate(zodSchema.changePasswordSchema),controllers.changeSuperAdminPassword);
router.route("/change-admin-password").post(validate(zodSchema.changePasswordSchema),controllers.changeAdminPassword);
router.route("/change-employee-password").post(validate(zodSchema.changePasswordSchema),controllers.changeEmployeePassword);
router.route("/send-mail").post(controllers.sendEmail);
module.exports = router;
